[profile.default]
solc = "0.8.27"
src = "src"
out = "out"
libs = ["dependencies"]
remappings = [
    "forge-std/=dependencies/forge-std-1.9.5/src/",
    "@openzeppelin/contracts/=dependencies/@openzeppelin-contracts-5.2.0/",
    "@ccip/=dependencies/smartcontractkit-ccip-2.17.0-ccip1.5.16/contracts/src/v0.8/",
    "@chainlink-local/=dependencies/chainlink-local-0.2.3/",
]

[dependencies]
forge-std = { version = "1.9.5" }
"@openzeppelin-contracts" = { version = "5.2.0" }
smartcontractkit-ccip = { version = "2.17.0-ccip1.5.16", git = "https://github.com/smartcontractkit/ccip.git", tag = "v2.17.0-ccip1.5.16" }
"chainlink-local" = { version = "0.2.3", git = "https://github.com/smartcontractkit/chainlink-local.git", tag = "v0.2.3" }

[soldeer]
remappings_generate = false
remappings_regenerate = false

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 128
fail_on_revert = false

[fmt]
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
