name: Test

on:
  push:
    branches:
      - main
      - release
      - develop
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: default

jobs:
  test:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    env:
      RPC_URL_SEPOLIA: ${{ secrets.RPC_URL_SEPOLIA }}
      RPC_URL_ARB_SEPOLIA: ${{ secrets.RPC_URL_ARB_SEPOLIA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install dependencies
        run: |
          make install

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          make test
        id: test
